name: build

on:
  workflow_dispatch:
    push:
      branches:
        - main

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          directory: /usr/local

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev

      - name: Build
        run: |
          ./pack.sh build
